// Hand-curated roster. Any field left null renders as "Unverified" in the UI.
// Subjective text fields should only be filled with sourced facts (see `sources`).
// To add a candidate: append a row, then run `npm run enrich` to pull photo/website/social.

const S = {
  senateIran: { label: 'Senate Iran war-powers votes (Jun 24 & Sep 24, 2026)', url: 'https://thehill.com/homenews/senate/5876248-senate-vote-war-powers-iran/' },
  houseIran: { label: 'House Iran war-powers votes (Jun 3 & Jul 23, 2026)', url: 'https://time.com/article/2026/07/23/war-powers-resolution-iran-trump-senate-house-republicans/' },
  distance: { label: 'Republicans distancing from Trump (Sep 2026)', url: 'https://spectrumlocalnews.com/us/snplus/politics/2026/09/22/republican-candidates-distance-themselves-from-trump-before-midterms' },
  senateRatings: { label: 'Cook Political Report Senate ratings', url: 'https://www.cookpolitical.com/ratings/senate-race-ratings' },
  govRatings: { label: '2026 gubernatorial ratings (Wikipedia aggregate)', url: 'https://en.wikipedia.org/wiki/2026_United_States_gubernatorial_elections' },
  houseRatings: { label: 'Cook Political Report House shifts (Sep 2026)', url: 'https://www.washingtonpost.com/elections/2026/09/25/cook-political-report-moves-15-house-races-into-democrats-favor/' },
  obbb: { label: 'OBBB final passage roll calls (Senate 51-50, Jul 1 2025; House 218-214, Jul 3 2025)', url: 'https://www.congress.gov/bill/119th-congress/house-bill/1' },
  epstein: { label: 'Epstein Files Transparency Act (H.R. 4405)', url: 'https://www.congress.gov/bill/119th-congress/house-bill/4405' },
  txSen: { label: 'Texas Senate polling after GOP runoff', url: 'https://thehill.com/homenews/campaign/5902035-texas-senate-race-poll/' },
  meSen: { label: 'Troy Jackson replaces Platner (NPR)', url: 'https://www.npr.org/2026/07/26/nx-s1-5906372/troy-jackson-replaces-graham-platner-as-democratic-candidate-in-maines-senate-race' },
  scSen: { label: 'South Carolina Senate race (Wikipedia)', url: 'https://en.wikipedia.org/wiki/2026_United_States_Senate_election_in_South_Carolina' },
  akGov: { label: 'Alaska governor primary results (Alaska Beacon)', url: 'https://alaskabeacon.com/2026/08/18/jkt-begich-wilson-and-bronson-lead-early-in-alaskas-primary-for-governor/' },
};

const SENATE_TOSSUP = 'Toss-up';
const NO_VOTE = 'Not a member of Congress';

// Senate vote facts. Senators who voted NO on OBBB: Collins, Paul, Tillis.
const sen = (o) => ({
  office: 'Senate',
  obbb: o.obbb ?? 'yes',
  epstein: 'Senate passed the Epstein Files Transparency Act by unanimous consent (Nov 2025).',
  ...o,
});
// House members: all Dems voted NO on OBBB final passage; Republicans YES except Massie & Fitzpatrick.
const hse = (o) => ({
  office: 'House',
  epstein: 'Voted YES on the Epstein Files Transparency Act (House passed 427-1, Nov 2025).',
  ...o,
});

export const roster = [
  // ───────────── SENATE ─────────────
  sen({ id: 'collins', name: 'Susan Collins', wiki: 'Susan_Collins', state: 'ME', party: 'R', status: 'Incumbent', race: 'Maine', rating: SENATE_TOSSUP, obbb: 'no',
    trump: null,
    iran: 'Voted YES on Democratic war-powers resolutions to end the Iran war (Jun 24: passed 50-48; Sep 24: failed 49-50).',
    distancing: 'Yes — skipping Trump\'s midterm convention; has repeatedly broken with him on war powers and OBBB.',
    polling: 'Cook: Toss-up; Lean D in several models (Economist, Silver, Split Ticket).',
    sources: [S.senateIran, S.distance, S.senateRatings, S.obbb] }),
  sen({ id: 'jackson-me', name: 'Troy Jackson', wiki: 'Troy_Jackson', state: 'ME', party: 'D', status: 'Challenger (nominee)', race: 'Maine', rating: SENATE_TOSSUP, obbb: NO_VOTE,
    epstein: null, trump: false,
    polling: 'Replaced Graham Platner as nominee at the Jul 25 convention after Platner withdrew Jul 10.',
    sources: [S.meSen, S.senateRatings] }),
  sen({ id: 'sullivan', name: 'Dan Sullivan', wiki: 'Dan_Sullivan_(U.S._senator)', state: 'AK', party: 'R', status: 'Incumbent', race: 'Alaska', rating: SENATE_TOSSUP, trump: null,
    iran: 'Voted NO on the Sep 24 war-powers resolution (only Paul, Collins, Murkowski, Tillis crossed over).',
    polling: 'Cook/Sabato/IE: Toss-up; Lean D in Silver Bulletin, DDHQ, Economist.',
    sources: [S.senateIran, S.senateRatings] }),
  sen({ id: 'peltola', name: 'Mary Peltola', wiki: 'Mary_Peltola', state: 'AK', party: 'D', status: 'Challenger (nominee)', race: 'Alaska', rating: SENATE_TOSSUP, obbb: NO_VOTE, epstein: null, trump: false,
    sources: [S.senateRatings] }),
  sen({ id: 'hinson', name: 'Ashley Hinson', wiki: 'Ashley_Hinson', state: 'IA', party: 'R', status: 'Open-seat nominee (current U.S. Rep.)', race: 'Iowa', rating: SENATE_TOSSUP, trump: true,
    obbb: 'yes', epstein: 'Voted YES on the Epstein Files Transparency Act (House, 427-1).',
    iran: 'No war-powers vote on record in sources found; says Iowans "shouldn\'t have to foot the bill at the pump… for the war in Iran."',
    distancing: 'Partial — criticizes war\'s cost at the pump while remaining Trump-endorsed.',
    polling: 'Toss-up (Cook, Sabato, IE, DDHQ); Lean D at Split Ticket.',
    sources: [S.distance, S.senateRatings] }),
  sen({ id: 'turek', name: 'Josh Turek', wiki: 'Josh_Turek', state: 'IA', party: 'D', status: 'Challenger (nominee)', race: 'Iowa', rating: SENATE_TOSSUP, obbb: NO_VOTE, epstein: null, trump: false,
    sources: [S.senateRatings] }),
  sen({ id: 'husted', name: 'Jon Husted', wiki: 'Jon_Husted', state: 'OH', party: 'R', status: 'Incumbent (appointed)', race: 'Ohio (special)', rating: SENATE_TOSSUP, trump: true,
    iran: 'Voted NO on the Sep 24 war-powers resolution.', polling: 'Toss-up (Cook, Sabato, IE); Lean D at Silver Bulletin and Economist.',
    sources: [S.senateIran, S.senateRatings, S.obbb] }),
  sen({ id: 'brown', name: 'Sherrod Brown', wiki: 'Sherrod_Brown', state: 'OH', party: 'D', status: 'Challenger (nominee)', race: 'Ohio (special)', rating: SENATE_TOSSUP, obbb: NO_VOTE, epstein: null, trump: false,
    sources: [S.senateRatings] }),
  sen({ id: 'paxton', name: 'Ken Paxton', wiki: 'Ken_Paxton', state: 'TX', party: 'R', status: 'Open-seat nominee (Texas AG)', race: 'Texas', rating: SENATE_TOSSUP, trump: true, antiDei: true, obbb: NO_VOTE, epstein: null,
    distancing: 'No — won the runoff over Sen. Cornyn with Trump\'s endorsement.',
    polling: 'Talarico 47, Paxton 44 (post-runoff poll, May 2026). Toss-up at Cook; Lean D at Silver Bulletin.',
    sources: [S.txSen, S.senateRatings] }),
  sen({ id: 'talarico', name: 'James Talarico', wiki: 'James_Talarico', state: 'TX', party: 'D', status: 'Open-seat nominee (state Rep.)', race: 'Texas', rating: SENATE_TOSSUP, obbb: NO_VOTE, epstein: null, trump: false,
    polling: 'Leads Paxton 47-44 in post-runoff polling; ~1/3 of Cornyn runoff voters said they would back the Democrat.',
    sources: [S.txSen, S.senateRatings] }),
  sen({ id: 'rogers', name: 'Mike Rogers', wiki: 'Mike_Rogers_(Michigan_politician)', state: 'MI', party: 'R', status: 'Open-seat nominee', race: 'Michigan', rating: SENATE_TOSSUP, trump: true, obbb: NO_VOTE, epstein: null,
    polling: 'Toss-up at Cook and Fox; Lean D at DDHQ, Economist, IE, Silver, Split Ticket.', sources: [S.senateRatings] }),
  sen({ id: 'elsayed', name: 'Abdul El-Sayed', wiki: 'Abdul_El-Sayed', state: 'MI', party: 'D', status: 'Open-seat nominee', race: 'Michigan', rating: SENATE_TOSSUP, obbb: NO_VOTE, epstein: null, trump: false,
    sources: [S.senateRatings] }),
  sen({ id: 'sununu', name: 'John E. Sununu', wiki: 'John_E._Sununu', state: 'NH', party: 'R', status: 'Open-seat nominee', race: 'New Hampshire', rating: SENATE_TOSSUP, obbb: NO_VOTE, epstein: null, trump: null,
    iran: 'Says he disagrees with Trump\'s handling of the Iran war and with his tariff policy.',
    distancing: 'Yes — disagrees on Iran & tariffs; not attending Trump\'s convention.',
    polling: 'Toss-up at Cook/IE; Likely D at several other forecasters.', sources: [S.distance, S.senateRatings] }),
  sen({ id: 'pappas', name: 'Chris Pappas', wiki: 'Chris_Pappas', state: 'NH', party: 'D', status: 'Open-seat nominee (current U.S. Rep.)', race: 'New Hampshire', rating: SENATE_TOSSUP, obbb: 'no', trump: false,
    epstein: 'Voted YES on the Epstein Files Transparency Act (House, 427-1).', sources: [S.senateRatings, S.obbb] }),
  sen({ id: 'whatley', name: 'Michael Whatley', wiki: 'Michael_Whatley', state: 'NC', party: 'R', status: 'Open-seat nominee', race: 'North Carolina', rating: 'Lean D', trump: true, obbb: NO_VOTE, epstein: null,
    polling: 'Lean D / Likely D at major forecasters (open seat, Tillis retiring).', sources: [S.senateRatings] }),
  sen({ id: 'cooper', name: 'Roy Cooper', wiki: 'Roy_Cooper', state: 'NC', party: 'D', status: 'Open-seat nominee', race: 'North Carolina', rating: 'Lean D', obbb: NO_VOTE, epstein: null, trump: false, sources: [S.senateRatings] }),
  sen({ id: 'marshall', name: 'Roger Marshall', wiki: 'Roger_Marshall', state: 'KS', party: 'R', status: 'Incumbent', race: 'Kansas', rating: 'Lean R', trump: true,
    iran: 'Voted NO on the Sep 24 war-powers resolution.', polling: 'Lean R at Cook, Fox, IE; a Toss-up at The Economist.', sources: [S.senateIran, S.senateRatings, S.obbb] }),
  sen({ id: 'hamilton', name: 'Adam Hamilton', wiki: null, state: 'KS', party: 'D', status: 'Challenger (nominee)', race: 'Kansas', rating: 'Lean R', obbb: NO_VOTE, epstein: null, trump: false, sources: [S.senateRatings] }),
  sen({ id: 'ricketts', name: 'Pete Ricketts', wiki: 'Pete_Ricketts', state: 'NE', party: 'R', status: 'Incumbent', race: 'Nebraska', rating: 'Lean R', trump: true,
    iran: 'Voted NO on the Sep 24 war-powers resolution.', polling: 'Lean R to Likely R; one forecaster rates Toss-up.', sources: [S.senateIran, S.senateRatings] }),
  sen({ id: 'osborn', name: 'Dan Osborn', wiki: 'Dan_Osborn', state: 'NE', party: 'I', status: 'Challenger (independent)', race: 'Nebraska', rating: 'Lean R', obbb: NO_VOTE, epstein: null, trump: false, sources: [S.senateRatings] }),
  sen({ id: 'dgraham', name: 'Darline Graham', wiki: null, state: 'SC', party: 'R', status: 'Incumbent (appointed)', race: 'South Carolina', rating: 'Lean R', trump: true, obbb: NO_VOTE, epstein: null,
    polling: 'Lean R to Likely R. Won Aug 25 runoff over Rep. Ralph Norman with Trump\'s support.', sources: [S.scSen] }),
  sen({ id: 'andrews', name: 'Annie Andrews', wiki: 'Annie_Andrews', state: 'SC', party: 'D', status: 'Challenger (nominee)', race: 'South Carolina', rating: 'Lean R', obbb: NO_VOTE, epstein: null, trump: false, sources: [S.scSen] }),

  // ───────────── GOVERNOR ─────────────
  { id: 'jackson-ga', name: 'Rick Jackson', wiki: 'Rick_Jackson_(businessman)', office: 'Governor', state: 'GA', party: 'R', status: 'Open-seat nominee', race: 'Georgia', rating: 'Toss-up', sources: [S.govRatings] },
  { id: 'bottoms', name: 'Keisha Lance Bottoms', wiki: 'Keisha_Lance_Bottoms', office: 'Governor', state: 'GA', party: 'D', status: 'Open-seat nominee', race: 'Georgia', rating: 'Toss-up', trump: false, sources: [S.govRatings] },
  { id: 'lombardo', name: 'Joe Lombardo', wiki: 'Joe_Lombardo', office: 'Governor', state: 'NV', party: 'R', status: 'Incumbent', race: 'Nevada', rating: 'Toss-up', trump: true, sources: [S.govRatings] },
  { id: 'ford', name: 'Aaron Ford', wiki: 'Aaron_D._Ford', office: 'Governor', state: 'NV', party: 'D', status: 'Challenger (state AG)', race: 'Nevada', rating: 'Toss-up', trump: false, sources: [S.govRatings] },
  { id: 'ramaswamy', name: 'Vivek Ramaswamy', wiki: 'Vivek_Ramaswamy', office: 'Governor', state: 'OH', party: 'R', status: 'Open-seat nominee', race: 'Ohio', rating: 'Toss-up', trump: true, antiDei: true,
    polling: 'Described as deadlocked with Amy Acton.', sources: [S.govRatings] },
  { id: 'acton', name: 'Amy Acton', wiki: 'Amy_Acton', office: 'Governor', state: 'OH', party: 'D', status: 'Open-seat nominee', race: 'Ohio', rating: 'Toss-up', trump: false, sources: [S.govRatings] },
  { id: 'tiffany', name: 'Tom Tiffany', wiki: 'Tom_Tiffany', office: 'Governor', state: 'WI', party: 'R', status: 'Open-seat nominee (current U.S. Rep.)', race: 'Wisconsin', rating: 'Toss-up', trump: true, obbb: 'yes', sources: [S.govRatings, S.obbb] },
  { id: 'crowley', name: 'David Crowley', wiki: 'David_Crowley_(politician)', office: 'Governor', state: 'WI', party: 'D', status: 'Open-seat nominee', race: 'Wisconsin', rating: 'Toss-up', trump: false, sources: [S.govRatings] },
  { id: 'kreiss-tomkins', name: 'Jonathan Kreiss-Tomkins', wiki: 'Jonathan_Kreiss-Tomkins', office: 'Governor', state: 'AK', party: 'D', status: 'Top-four finalist (ranked-choice)', race: 'Alaska', rating: 'Toss-up', trump: false,
    polling: 'Led the Aug 18 primary with 22.5%.', sources: [S.akGov, S.govRatings] },
  { id: 'wilson-ak', name: 'Bernadette Wilson', wiki: 'Bernadette_Wilson', office: 'Governor', state: 'AK', party: 'R', status: 'Top-four finalist (ranked-choice)', race: 'Alaska', rating: 'Toss-up', polling: 'Finished third in the primary with 10%.', sources: [S.akGov] },
  { id: 'bronson', name: 'Dave Bronson', wiki: 'Dave_Bronson', office: 'Governor', state: 'AK', party: 'R', status: 'Top-four finalist (ranked-choice)', race: 'Alaska', rating: 'Toss-up', polling: 'Finished fourth in the primary with 8.1%.', sources: [S.akGov] },
  { id: 'lahn', name: 'Zach Lahn', wiki: null, office: 'Governor', state: 'IA', party: 'R', status: 'Open-seat nominee', race: 'Iowa', rating: 'Lean D', sources: [S.govRatings] },
  { id: 'sand', name: 'Rob Sand', wiki: 'Rob_Sand', office: 'Governor', state: 'IA', party: 'D', status: 'Open-seat nominee (state auditor)', race: 'Iowa', rating: 'Lean D', trump: false, sources: [S.govRatings] },
  { id: 'biggs', name: 'Andy Biggs', wiki: 'Andy_Biggs', office: 'Governor', state: 'AZ', party: 'R', status: 'Challenger (current U.S. Rep.)', race: 'Arizona', rating: 'Lean D', trump: true, obbb: 'yes',
    epstein: 'House member; voted YES on the Epstein Files Transparency Act (427-1).', sources: [S.govRatings, S.obbb] },
  { id: 'hobbs', name: 'Katie Hobbs', wiki: 'Katie_Hobbs', office: 'Governor', state: 'AZ', party: 'D', status: 'Incumbent', race: 'Arizona', rating: 'Lean D', trump: false, sources: [S.govRatings] },
  { id: 'james', name: 'John James', wiki: 'John_James_(Michigan_politician)', office: 'Governor', state: 'MI', party: 'R', status: 'Open-seat nominee (current U.S. Rep.)', race: 'Michigan', rating: 'Lean D', obbb: 'yes',
    epstein: 'House member; voted YES on the Epstein Files Transparency Act (427-1).', sources: [S.govRatings, S.obbb] },
  { id: 'benson', name: 'Jocelyn Benson', wiki: 'Jocelyn_Benson', office: 'Governor', state: 'MI', party: 'D', status: 'Open-seat nominee', race: 'Michigan', rating: 'Lean D', trump: false, sources: [S.govRatings] },
  { id: 'donalds', name: 'Byron Donalds', wiki: 'Byron_Donalds', office: 'Governor', state: 'FL', party: 'R', status: 'Open-seat nominee (current U.S. Rep.)', race: 'Florida', rating: 'Lean R', trump: true, obbb: 'yes',
    epstein: 'House member; voted YES on the Epstein Files Transparency Act (427-1).', polling: 'Lean R at most; Toss-up at RCP & DDHQ.', sources: [S.govRatings, S.obbb] },
  { id: 'jolly', name: 'David Jolly', wiki: 'David_Jolly', office: 'Governor', state: 'FL', party: 'D', status: 'Open-seat nominee', race: 'Florida', rating: 'Lean R', trump: false, sources: [S.govRatings] },
  { id: 'masterson', name: 'Ty Masterson', wiki: 'Ty_Masterson', office: 'Governor', state: 'KS', party: 'R', status: 'Open-seat nominee', race: 'Kansas', rating: 'Lean R', sources: [S.govRatings] },
  { id: 'holscher', name: 'Cindy Holscher', wiki: 'Cindy_Holscher', office: 'Governor', state: 'KS', party: 'D', status: 'Open-seat nominee', race: 'Kansas', rating: 'Lean R', trump: false, sources: [S.govRatings] },
  { id: 'abbott', name: 'Greg Abbott', wiki: 'Greg_Abbott', office: 'Governor', state: 'TX', party: 'R', status: 'Incumbent', race: 'Texas', rating: 'Lean R', trump: true, sources: [S.govRatings] },
  { id: 'hinojosa', name: 'Gina Hinojosa', wiki: 'Gina_Hinojosa', office: 'Governor', state: 'TX', party: 'D', status: 'Challenger (nominee)', race: 'Texas', rating: 'Lean R', trump: false, sources: [S.govRatings] },
  { id: 'ayotte', name: 'Kelly Ayotte', wiki: 'Kelly_Ayotte', office: 'Governor', state: 'NH', party: 'R', status: 'Incumbent', race: 'New Hampshire', rating: 'Likely R', sources: [S.govRatings, S.distance] },

  // ───────────── HOUSE (Cook toss-up incumbents, Sep 2026) ─────────────
  hse({ id: 'gray', name: 'Adam Gray', wiki: 'Adam_Gray_(politician)', state: 'CA', district: '13', party: 'D', status: 'Incumbent', race: 'CA-13', rating: 'Toss-up', obbb: 'no', trump: false, sources: [S.houseRatings] }),
  hse({ id: 'tran', name: 'Derek Tran', wiki: 'Derek_Tran', state: 'CA', district: '45', party: 'D', status: 'Incumbent', race: 'CA-45', rating: 'Toss-up', obbb: 'no', trump: false, sources: [S.houseRatings] }),
  hse({ id: 'vasquez', name: 'Gabe Vasquez', wiki: 'Gabe_Vasquez', state: 'NM', district: '02', party: 'D', status: 'Incumbent', race: 'NM-02', rating: 'Toss-up', obbb: 'no', trump: false, sources: [S.houseRatings] }),
  hse({ id: 'gillen', name: 'Laura Gillen', wiki: 'Laura_Gillen', state: 'NY', district: '04', party: 'D', status: 'Incumbent', race: 'NY-04', rating: 'Toss-up', obbb: 'no', trump: false, sources: [S.houseRatings] }),
  hse({ id: 'davis', name: 'Don Davis', wiki: 'Don_Davis_(North_Carolina_politician)', state: 'NC', district: '01', party: 'D', status: 'Incumbent', race: 'NC-01', rating: 'Toss-up', obbb: 'no', trump: false, sources: [S.houseRatings] }),
  hse({ id: 'kaptur', name: 'Marcy Kaptur', wiki: 'Marcy_Kaptur', state: 'OH', district: '09', party: 'D', status: 'Incumbent', race: 'OH-09', rating: 'Toss-up', obbb: 'no', trump: false, sources: [S.houseRatings] }),
  hse({ id: 'sykes', name: 'Emilia Sykes', wiki: 'Emilia_Sykes', state: 'OH', district: '13', party: 'D', status: 'Incumbent', race: 'OH-13', rating: 'Toss-up', obbb: 'no', trump: false, sources: [S.houseRatings] }),
  hse({ id: 'gonzalez', name: 'Vicente Gonzalez', wiki: 'Vicente_Gonzalez', state: 'TX', district: '34', party: 'D', status: 'Incumbent', race: 'TX-34', rating: 'Toss-up', obbb: 'no', trump: false, sources: [S.houseRatings] }),
  hse({ id: 'gluesenkamp-perez', name: 'Marie Gluesenkamp Perez', wiki: 'Marie_Gluesenkamp_Perez', state: 'WA', district: '03', party: 'D', status: 'Incumbent', race: 'WA-03', rating: 'Toss-up', obbb: 'no', trump: false, sources: [S.houseRatings] }),
  hse({ id: 'ciscomani', name: 'Juan Ciscomani', wiki: 'Juan_Ciscomani', state: 'AZ', district: '06', party: 'R', status: 'Incumbent', race: 'AZ-06', rating: 'Toss-up', obbb: 'yes', sources: [S.houseRatings, S.obbb] }),
  hse({ id: 'evans', name: 'Gabe Evans', wiki: 'Gabe_Evans', state: 'CO', district: '08', party: 'R', status: 'Incumbent', race: 'CO-08', rating: 'Toss-up', obbb: 'yes', sources: [S.houseRatings, S.obbb] }),
  hse({ id: 'miller-meeks', name: 'Mariannette Miller-Meeks', wiki: 'Mariannette_Miller-Meeks', state: 'IA', district: '01', party: 'R', status: 'Incumbent', race: 'IA-01', rating: 'Toss-up', obbb: 'yes', sources: [S.houseRatings, S.obbb] }),
  hse({ id: 'barrett', name: 'Tom Barrett', wiki: 'Tom_Barrett_(Michigan_politician)', state: 'MI', district: '07', party: 'R', status: 'Incumbent', race: 'MI-07', rating: 'Toss-up', obbb: 'yes',
    iran: 'One of four House Republicans (with Massie, Fitzpatrick, Davidson) who voted YES on both Iran war-powers resolutions (215-208 Jun 3; 214-208 Jul 23).',
    distancing: 'Yes on Iran war powers; otherwise votes with the party on OBBB.', sources: [S.houseIran, S.houseRatings, S.obbb] }),
  hse({ id: 'mackenzie', name: 'Ryan Mackenzie', wiki: 'Ryan_Mackenzie', state: 'PA', district: '07', party: 'R', status: 'Incumbent', race: 'PA-07', rating: 'Toss-up', obbb: 'yes', sources: [S.houseRatings, S.obbb] }),
  hse({ id: 'perry', name: 'Scott Perry', wiki: 'Scott_Perry', state: 'PA', district: '10', party: 'R', status: 'Incumbent', race: 'PA-10', rating: 'Toss-up', obbb: 'yes', sources: [S.houseRatings, S.obbb] }),
  hse({ id: 'fitzpatrick', name: 'Brian Fitzpatrick', wiki: 'Brian_Fitzpatrick_(politician)', state: 'PA', district: '01', party: 'R', status: 'Incumbent', race: 'PA-01', rating: null, obbb: 'no',
    iran: 'Voted YES on both House Iran war-powers resolutions, citing the War Powers Act.',
    distancing: 'Yes — voted against OBBB final passage and for Iran war-powers limits.', sources: [S.houseIran, S.obbb] }),
];
